from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('profile/', views.profile, name='profile'),
    path('funds/', views.fund_list, name='fund_list'),
    path('invest/<int:pk>/', views.invest_in_fund, name='invest_in_fund'),
    path('investments/', views.active_investments, name='active_investments'),
    path('payments/', views.payment, name='payment'),
    path('kyc/apply/', views.apply_kyc, name='apply_kyc'),
    path('kyc/status/', views.kyc_status, name='kyc_status'),
    path('kyc/review/<int:pk>/', views.kyc_review_detail, name='kyc_review_detail'),
    path('agreements/', views.agreement_list, name='agreement_list'),
    path('agreements/<int:pk>/download/', views.agreement_download, name='agreement_download'),
    path('fund-agreements/<int:pk>/download/', views.fund_agreement_download, name='fund_agreement_download'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/', views.admin_dashboard, name='admin_dashboard_alias'),
    path('admin/investors/', views.admin_investors, name='admin_investors'),
    path('admin/funds/', views.admin_funds, name='admin_funds'),
    path('admin/funds/<int:pk>/toggle/', views.admin_toggle_fund, name='admin_toggle_fund'),
    path('admin/funds/<int:pk>/delete/', views.admin_delete_fund, name='admin_delete_fund'),
    path('admin/add-fund/', views.admin_add_fund, name='admin_add_fund'),
    path('admin/fund-applications/', views.admin_fund_applications, name='admin_fund_applications'),
    path('admin/reports/', views.admin_reports, name='admin_reports'),
    path('admin/reports/download/', views.admin_reports_download, name='admin_reports_download'),
    path('admin/pending-payments/', views.admin_pending_payments, name='admin_pending_payments'),
    path('admin/investor-overview/', views.admin_investor_funds_overview, name='admin_investor_funds_overview'),
    path('admin/investor/<int:investor_id>/detail/', views.admin_investor_detail, name='admin_investor_detail'),
    path('send-reminder/', views.send_monthly_reminder, name='send_reminder'),
    path('investment-history/', views.investment_history, name='investment_history'),
    path('pending-payments/', views.investor_pending_payments, name='investor_pending_payments'),
    path('submit-payment/<int:investment_id>/', views.submit_monthly_payment, name='submit_monthly_payment'),
    path('investment-report/<int:investment_id>/', views.investment_report_detail, name='investment_report_detail'),
    path('ssl-pay/<int:pk>/', views.ssl_payment, name='ssl_payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/fail/', views.payment_fail, name='payment_fail'),
    path('payment/cancel/', views.payment_cancel, name='payment_cancel'),
]
