# Generated by Django 6.0.4 on 2026-05-01 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_account', models.CharField(max_length=100)),
                ('income_source', models.CharField(max_length=255)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='kyc/id_proof/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='kyc/bank_statement/')),
                ('wealth_declaration', models.FileField(blank=True, null=True, upload_to='kyc/wealth_declaration/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('additional_docs', 'Additional Documents Required')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('requested_documents', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='agreements/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='accounts.investorkyc')),
            ],
        ),
    ]
