# Generated by Django 6.0.4 on 2026-05-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fund_investment_installment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
