# Generated by Django 6.0.4 on 2026-05-02 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_investment_created_at_investment_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.investment'),
        ),
    ]
