# Generated by Django 6.0.4 on 2026-05-11 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_payment_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='total_capacity',
        ),
        migrations.AddField(
            model_name='payment',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.investment'),
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
