# Generated by Django 6.0.4 on 2026-06-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_payment_installment_remove_fund_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
