# Generated by Django 6.0.4 on 2026-06-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_fund_monthly_installment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='minimum_investment',
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
