# Generated by Django 6.0.4 on 2026-06-01 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_fund_minimum_investment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='agreements/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='accounts.fund')),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_agreement', to='accounts.investment')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_agreements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
